[tox]
envlist = ruff, py, coverage-report

[testenv]
deps = -r{toxinidir}/requirements/tests
commands = coverage run -m pytest {posargs:tests}

[testenv:nocover]
deps = -r{toxinidir}/requirements/tests
commands = pytest {posargs:tests}

# --------------------------------------------------------------------
# Style
# --------------------------------------------------------------------

[testenv:ruff]
skip_install = true
deps =
    ruff >= 0.15.0
commands =
    ruff check
    ruff format --check

[testenv:reformat]
deps =
    ruff >= 0.15.0
skip_install = True
commands =
    ruff format
    ruff check --fix

# --------------------------------------------------------------------
# Coverage
# --------------------------------------------------------------------

[testenv:coverage-report]
skip_install = true
commands =
    coverage combine
    coverage html -d .coverage_html
    coverage report

# --------------------------------------------------------------------
# Documentation
# --------------------------------------------------------------------

# TODO
