[tox]
envlist = ruff, typing, py, coverage-report

# --------------------------------------------------------------------
# Unit tests
# --------------------------------------------------------------------

[testenv]
deps = -r{toxinidir}/requirements/tests
commands = coverage run -m pytest {posargs:tests}

[testenv:nocover]
deps = -r{toxinidir}/requirements/tests
commands = pytest {posargs:tests}

# --------------------------------------------------------------------
# Typing
# --------------------------------------------------------------------

[testenv:typing]
deps =
    mypy
commands =
    mypy --strict token_bucket/

# --------------------------------------------------------------------
# Style
# --------------------------------------------------------------------

[testenv:ruff]
skip_install = true
deps =
    ruff >= 0.15.0
commands =
    ruff check
    ruff format --check

[testenv:reformat]
deps =
    ruff >= 0.15.0
skip_install = True
commands =
    ruff format
    ruff check --fix

# --------------------------------------------------------------------
# Packaging
# --------------------------------------------------------------------

[testenv:twine-check]
skipsdist = True
deps = build
       twine
commands =
    python -m build
    twine check {toxinidir}/dist/*

# --------------------------------------------------------------------
# Coverage
# --------------------------------------------------------------------

[testenv:coverage-report]
skip_install = true
commands =
    coverage combine
    coverage html -d .coverage_html
    coverage report

# --------------------------------------------------------------------
# Documentation
# --------------------------------------------------------------------

# TODO
